version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: envhealth_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./src:/app/src
    restart: always

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: envhealth_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
    restart: always
